[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
kinobi_test = "3eSEGBd6d6C6imYBaeu9vDJqf4cCjxPE1JkX5TaagJCD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
